name: Update Version

on:
  push:
    branches:
      - main

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update Version
        run: |
          git config --local user.email "thiagosantosgg0@gmail.com"
          git config --local user.name "thiagosantos"
          COMMIT_VERSION=$(git rev-parse --short HEAD)
          CURRENT_DATE=$(date +"%d/%m/%Y %H:%M:%S")
          sed -i "s|image_tag: .*|image_tag: $COMMIT_VERSION|" image-tag.yaml
          sed -i "s|date: .*|date: $CURRENT_DATE|" image-tag.yaml
          git add image-tag.yaml
          git commit -m "Update image_tag and date to $COMMIT_VERSION on $CURRENT_DATE"
          git push
